version: '2.0'
language: vi
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 50
    constrain_similarities: true
    model_confidence: softmax
  - name: EntitySynonymMapper
  - name: FallbackClassifier
    threshold: 0.2
    ambiguity_threshold: 0.05
  - name: "DucklingEntityExtractor"
    url: "http://localhost:8000"
    locale: "vi_VI"
    dimensions: ["time", "number","numeral", "amount-of-money"]
  - name: ResponseSelector
    epochs: 100

# policies:
#   - name: MemoizationPolicy
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 40
#     constrain_similarities: true
#   - name: RulePolicy
#     core_fallback_threshold: 0.1
#     core_fallback_action_name: "action_default_fallback"
#     enable_fallback_prediction: True


# version: "2.0"
# language: vi

# pipeline:
# - name: VietnameseTokenizer
# - name: LexicalSyntacticFeaturizer
# - name: CountVectorsFeaturizer
#   analyzer: char_wb
#   min_ngram: 1
#   max_ngram: 4
# - name: rasa_nlu_examples.featurizers.dense.FastTextFeaturizer
#   cache_dir: lib/fastText
#   file: cc.vi.300.bin
# - name: DIETClassifier
#   epochs: 500
#   model_confidence: softmax
# - name: EntitySynonymMapper
# - name: FallbackClassifier
#   threshold: 0.2
#   ambiguity_threshold: 0.1
# - name: "DucklingEntityExtractor"
#   url: "http://localhost:8000"
#   locale: "vi_VI"
#   dimensions: ["time", "number","numeral", "amount-of-money"]
# - name: ResponseSelector
#   epochs: 100

# pipeline:
#   - name: HFTransformersNLP
#     model_name: "phobert"
#     model_weights: "vinai/phobert-base"
#   - name: LanguageModelTokenizer
#   - name: LanguageModelFeaturizer
#   - name: DIETClassifier
#     epochs: 300
#     constrain_similarities: true
#     model_confidence: softmax
#   - name: EntitySynonymMapper
#   - name: FallbackClassifier
#     threshold: 0.5
#     ambiguity_threshold: 0.05
#   - name: "DucklingEntityExtractor"
#     url: "http://localhost:8000"
#     locale: "vi_VI"
#     dimensions: ["time", "number","numeral", "amount-of-money"]

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 50
    constrain_similarities: true
  - name: RulePolicy
    core_fallback_threshold: 0.1
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True

